### ISSUE TITLE
package can't be defined as external in rollup config

### ISSUE THREAD

**Issue by plastikfan** [neet/i18next-cli-language-detector#118]
When using [rollup](https://rollupjs.org/) bundler, it is necessary to define dependencies as [external](https://rollupjs.org/guide/en/#external), but doing so for __I18nextCLILanguageDetector__ causes the following error when passing in I18nextCLILanguageDetector to next.use:

> Error: You are passing a wrong module! Please check the object you are passing to i18next.use()

```js
import i18next from "i18next";
import Backend from "i18next-fs-backend";
import I18nextCLILanguageDetector from "i18next-cli-language-detector";

const OUT = "dist";
const EN = "en";
const EN_US = "en-US";
const TRANSLATION = "translation";

const inoptions = {
  backend: {
    loadPath: `./${OUT}/locales/{{lng}}/{{ns}}.json`
  },
  lng: EN,
  fallbackLng: EN,
  preload: [EN, EN_US],
  ns: [TRANSLATION],
  defaultNS: TRANSLATION
};

await i18next
  .use(I18nextCLILanguageDetector)
  .use(Backend)
  .init(inoptions, (err, t) => {
    if (err) return console.error(err);

    console.log(`US: '${t("i18n", { lng: EN_US })}'`);
    console.log(`GB: '${t("i18n")}'`);
  });
```

Every module passed into i18next.use, must have a type property. In this example I show, the Backend module works ok because it's type property is set to "Backend". When I look at the I18nextCLILanguageDetector module, it does not have a type property so this error is thrown. So the question is why doesnt it have a type property? Having taken a look at the implementation of use in i18next, I can see that its expecting a type property = "languageDetector", but it is missing:

__i18next__:

```js
{
    key: "use",
    value: function use(module) {
      if (!module) throw new Error('You are passing an undefined module! Please check the object you are passing to i18next.use()');
      if (!module.type) throw new Error('You are passing a wrong module! Please check the object you are passing to i18next.use()');

      if (module.type === 'backend') {
        this.modules.backend = module;
      }

      if (module.type === 'logger' || module.log && module.warn && module.error) {
        this.modules.logger = module;
      }

      if (module.type === 'languageDetector') {
        this.modules.languageDetector = module;
      }
...
```

and the really strange this is that I do see this in I18nextCLILanguageDetector

```js
...
    I18nextCLILanguageDetector.type = 'languageDetector';
    return I18nextCLILanguageDetector;
```

so somehow, the type is being stripped off when its imported, but only when rollup externalises  __I18nextCLILanguageDetector__. Now I have taken a look at the source code for [__i18next-fs-backend__](https://www.npmjs.com/package/i18next-fs-backend) and I can see that it appears to have more code to support esm modules vs commonjs modules, which does appear to be missing from __I18nextCLILanguageDetector__ and is perhaps the cause of the issue. The same actually does for [__i18nest__](https://www.npmjs.com/package/i18next), which also does not suffer this problem when added to rollup external.

I am going to do a bit more research into weeds of rollup to see if I can shed some light on this, but you may indeed may know what the problem is.

I do have a workaround for the time being and that is is to not externalise the package in the rollup config, so its not the end of the world for now.

PS: I am iusing this in a typescript context inside an esm package.

**Comment by neet** [comment]
Hi, again @plastikfan. I believe this issue kind of related to another issue I've known: when you use i18next-cli-language-detector in CJS, you need to [`const { default as LanguageDetector }` instead of `const LanguageDetector`](https://github.com/neet/i18next-cli-language-detector/blob/main/e2e/test.cjs#L3) for some reasons. Not many people write CJS directly these days so I didn't document/fix this issue, however. 

I associated it because the error message you posted is exactly the same as an error message you'd get when you did `const LanguageDetector` in CJS. I have not yet confirmed it actually matters regarding this issue, but I think it's worth giving it a try.

Also, as you mentioned, supporting ESM natively would be another solution for this.

I also will reserach on this, but since I'm not familiar with `rollup-external`'s behaviour or its combination with ESM, it'd be great if you post some updates or a full reproduction repository.

**Comment by plastikfan** [comment]
Hi @neet, I've put out a few feelers on this issue, but have not got an answer yet, so still investigating. As a result of your comment about the import statment I tried te following:

> import { default as I18nextCLILanguageDetector } from "i18next-cli-language-detector";

but that didnt work, so I'm still scratching my head! Thanks for taking the time to look into this, hopefully between us we can solve it. I wont be able to look into this today though as I'm away attending to other errands, but I'll update you as soon as I can.

**Comment by neet** [comment]
I tried out bundling this plugin with rollup, but I could not reproduce the error described above. The full source code here https://github.com/neetlab/i18next-cli-118-repro

![image](https://user-images.githubusercontent.com/19276905/143679227-12688f39-fcb7-497e-a9c8-425f776a9fde.png)

@plastikfan Would you elaborate more of your environment / the full configuration of `tsconfig.json` or `rollup.config.js`? it'd be even better if you can publish the minimal setup on Github which I can run on my machine.

**Comment by plastikfan** [comment]
Well that's interesting @neet and actually that goods news because it'll mean that I have done something wrong. I am building an esm starter template project which is this: [nodejs-esm-starter](https://github.com/Snivilization/nodejs-esm-starter) ...

**Comment by plastikfan** [comment]
actually, I might not have checkedd in the code, hold on a sec ...

**Comment by plastikfan** [comment]
Ok i've pushed my changes onto a separate branch chore/i18n-language-detect. Just clone the project, switch to chore/i18n-language-detect branch, install, then run "npm run dev".

**Comment by neet** [comment]
@plastikfan Thank you very much! I'll look into it

**Comment by plastikfan** [comment]
The key part to look at is rollup/ptions.mjs. You will see that I set up an externals object that is exported. Inside are arrays for source and test and you will see that for source, I have added "i18next-cli-language-detector" to it. I am going to look at your project to see if I can spot any key differences. Perhaps its a setting in typescript ....

**Comment by neet** [comment]
I could reproduce your error. What is interesting is by `console.log`ging I could see `I18nextCLILanguageDetector` we imported is an object that has `default` key (so my guess was close)

```diff
/* around line :3 */
import I18nextCLILanguageDetector from "i18next-cli-language-detector";

+ console.log('[I18nextCLILanguageDetector]', I18nextCLILanguageDetector);
```

![image](https://user-images.githubusercontent.com/19276905/143680361-126d2c10-d654-4c4b-9126-e3dacd3d303a.png)

So, this is not the final solution but as a workaround you can circunvemnt the error by `.default` key access

```diff
/* around line :40 in src/main.ts */
await i18next
+  // @ts-ignore
+  .use(I18nextCLILanguageDetector.default)
```

**Comment by neet** [comment]
I still have no idea the difference of rollup config between my repro and nodejs-esm-starter because of the way @plastikfan setup rollup config is a pro... 

Anyways, I ended up thinking the way I could solve this issue is to fix the bug I mentioned above that the default export is converted to a named export as 'default' property. So I created a patch on #119 which fixes it and also supports ESM.

I published the patch under the `next` tag so you can check it out by:

```
npm install i18next-cli-language-detector@1.1.0-rc1
```

**Comment by plastikfan** [comment]
That's great thank you
